# fly.toml app configuration file generated for 3x-ui-z on 2025-04-29T19:24:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '3x-ui-z'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 2053
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type       = "connections"
    soft_limit = 99999
    hard_limit = 9999999999

#[[mounts]]
#  source = "data_vol"
#  destination = "/etc/x-ui"

[[services]]
  internal_port = 63396
  protocol = "tcp"
  handlers = []
  [[services.ports]]
    port = 63396
